name: Build and Deploy to EC2

on:
  push:
    branches:
      - dev # Trigger this workflow on every push to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platform: linux/amd64
          push: true
          tags: damolacodes/diimu-api:1.0
  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PEM_KEY }}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USERNAME }}
        run: |
          # Set up SSH key
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          
          # Create a deployment script
          cat > deploy_script.sh << 'EOF'
          #!/bin/bash
          set -e
          echo "--- Starting deployment on EC2 ---"
          # IMPORTANT: Navigate to the directory containing your docker-compose.yml file
          # cd /path/to/your/project
          
          # Pull the latest image and restart the services
          sudo docker compose pull
          sudo docker compose up -d
          
          echo "--- App deployed successfully ---"
          EOF
          
          # Copy the script to the EC2 instance
          scp -o StrictHostKeyChecking=no -i private_key deploy_script.sh ${USER_NAME}@${HOSTNAME}:/tmp/deploy_script.sh
          
          # Execute the script on the EC2 instance
          ssh -T -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "bash /tmp/deploy_script.sh"

